# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{detect_browser_os}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Ryan Sonnek}]
  s.date = %q{2011-09-12}
  s.description = %q{add css classes to your markup based on the end users browser and operating system.}
  s.email = %q{ryan@socialcast.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "detect_browser_os.gemspec",
    "lib/detect_browser_os.rb",
    "test/helper.rb",
    "test/test_detect_browser_os.rb"
  ]
  s.homepage = %q{http://github.com/wireframe/detect_browser_os}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{add css classes to your markup based on the end users browser and operating system.}
  s.test_files = [
    "test/helper.rb",
    "test/test_detect_browser_os.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

